name: Deploy Infrastructure

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # Debug: Print who is assuming the role
      - name: Who am I
        run : |
          CREDS=$(aws sts assume-role --role-arn ${{ secrets.AWS_IAM_ROLE_ARN }} --role-session-name assumed-role --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | cut -f1)
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | cut -f2)
          export AWS_SESSION_TOKEN=$(echo $CREDS | cut -f3)

          # Debug: Print who is assuming the role
          aws sts get-caller-identity


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve tfplan
